import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Page from "./component/page";
const inter = Inter({ subsets: ["latin"] });
import Footer from "./component/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >
        <div className="mx-w-[90%] mx-auto bg-emerald-50"  >
        <Page/>
        {children}
        <Footer/>
        </div>
        </body>
    </html>
  );
}
